<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10877" started-at="2020-06-30T16:13:42 ICT" finished-at="2020-06-30T16:13:52 ICT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10877" started-at="2020-06-30T16:13:42 ICT" finished-at="2020-06-30T16:13:52 ICT">
      <class name="poly.Test.TestSendMail">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:poly.Test.TestSendMail@16267862]" name="launchBrowser" is-config="true" duration-ms="4832" started-at="2020-06-30T16:13:42 ICT" finished-at="2020-06-30T16:13:46 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="veryfyHomePageTitle()[pri:0, instance:poly.Test.TestSendMail@16267862]" name="veryfyHomePageTitle" duration-ms="225" started-at="2020-06-30T16:13:46 ICT" finished-at="2020-06-30T16:13:47 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veryfyHomePageTitle -->
        <test-method status="PASS" signature="LoginTest()[pri:1, instance:poly.Test.TestSendMail@16267862]" name="LoginTest" duration-ms="3001" started-at="2020-06-30T16:13:47 ICT" finished-at="2020-06-30T16:13:50 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="Testmail1()[pri:2, instance:poly.Test.TestSendMail@16267862]" name="Testmail1" duration-ms="1505" started-at="2020-06-30T16:13:50 ICT" finished-at="2020-06-30T16:13:51 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testmail1 -->
        <test-method status="FAIL" signature="Testmail2()[pri:3, instance:poly.Test.TestSendMail@16267862]" name="Testmail2" duration-ms="564" started-at="2020-06-30T16:13:51 ICT" finished-at="2020-06-30T16:13:52 ICT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at poly.Test.TestSendMail.Testmail2(TestSendMail.java:162)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testmail2 -->
        <test-method status="PASS" signature="suiteTearDown()[pri:0, instance:poly.Test.TestSendMail@16267862]" name="suiteTearDown" is-config="true" duration-ms="687" started-at="2020-06-30T16:13:52 ICT" finished-at="2020-06-30T16:13:52 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteTearDown -->
      </class> <!-- poly.Test.TestSendMail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
